name: leigod auto pause action

on:
  push:
  workflow_dispatch:
  schedule:
    # 定时任务，北京时间3点执行任务 19 + 8 = 27 % 24 = 3
    - cron: '0 19 * * *'

jobs:
  pause:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 24.x
        uses: actions/setup-node@v5
        with:
          node-version: 24.x
      - name: Run npm install
        run: |
          npm install
      - name: Run node index.js
        run: |
          node index.js
        env:
          LEIGOD_TOKENS: ${{ secrets.LEIGOD_TOKENS }}
          USERNAME_ARR: ${{ secrets.USERNAME_ARR }}
          PASSWORD_ARR: ${{ secrets.PASSWORD_ARR }}
